---
- name: Fetch sensitive lobby parameters
  hosts: wfg-lobby
  tasks:
    - name: Fetch Ansible variable file with sensitive lobby parameters
      ansible.builtin.fetch:
        src: /root/lobby-config.yml
        dest: "{{ playbook_dir }}/lobby-config.yml"
      become: true
