---
- name: Provision lobby
  hosts: all
  become: true
  pre_tasks:
    - name: Load lobby config
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/config-{{ inventory_hostname }}.yml"
  roles:
    - apt
    - ssh
    - misc
    - users
    - certbot
    - openssl
    - ejabberd
    - ejabberd_registration_log
    - python
    - lobby_bots
    - borgmatic
  post_tasks:
    - name: Push Ansible variable file with sensitive lobby parameters
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/config-{{ inventory_hostname }}.yml"
        dest: /root/lobby-config.yml
        owner: root
        group: root
        mode: 0600
