---
- name: Set the default umask to 077
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^UMASK\t'
    line: "UMASK\t\t077"
    state: present

- name: Use pam_umask to enforce the file mode creation umask
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-session
    regexp: 'pam_umask\.so'
    line: "session\toptional\tpam_umask.so"
    state: present

- name: Get all skeleton files
  ansible.builtin.find:
    paths: /etc/skel
    hidden: true
    recurse: true
  register: skeleton_files

- name: Change file permissions of skeleton files
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: 0700
  loop: "{{ skeleton_files.files }}"

- name: Ensure undesired ntp services aren't installed
  ansible.builtin.apt:
    name:
      - chrony
      - ntp
      - rsyslog
    state: absent
    purge: true

- name: Install some additional packages
  ansible.builtin.apt:
    name:
      - aptitude
      - bash
      - curl
      - git
      - hdparm
      - iftop
      - iotop
      - iptables
      - less
      - lsof
      - lvm2
      - molly-guard
      - mtr-tiny
      - nano
      - net-tools
      - nmap
      - rsync
      - screen
      - sqlite3
      - sudo
      - systemd-timesyncd
      - tzdata
      - zstd
    state: present

- name: Ensure timezone is set to UTC
  ansible.builtin.file:
    src: /usr/share/zoneinfo/Etc/UTC
    path: /etc/localtime
    owner: root
    group: root
    state: link

- name: Enable systemd timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    state: started

- name: Create directory for journald config drop-ins
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Configure journald
  ansible.builtin.copy:
    src: journal-size.conf
    dest: /etc/systemd/journald.conf.d/journal-size.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart journald

# That's a workaround to ensure the bots always connect to localhost,
# as Slixmpp currently doesn't honor explicitly configured addresses
# used to connect for reconnections.
- name: Let configured domains resolve to localhost
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1\tlocalhost{%- for domain in domains %} {{ domain }}{%- endfor -%}"
